### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by webular** [ads1018/next-apollo-example#1]
npm install
npm run dev

When I try to visit localhost:3000 i get the following:

`TypeError: Cannot read property 'apply' of undefined
eval
http://localhost:3000/_next/commons.js:8668:3
createStore
http://localhost:3000/_next/commons.js:8668:3
initStore
http://localhost:3000/_next/commons.js:8668:3
new _class
http://localhost:3000/_next/commons.js:8668:3
http://localhost:3000/_next/main.js:20029:24
instantiate
http://localhost:3000/_next/main.js:20037:9
_class
http://localhost:3000/_next/main.js:20044:22
http://localhost:3000/_next/main.js:12081:18
measureLifeCyclePerf
http://localhost:3000/_next/main.js:11861:12
ReactCompositeComponentWrapper._constructComponentWithoutOwner
http://localhost:3000/_next/main.js:12080:16`

Any thoughts?

**Comment by ads1018** [comment]
hmm I'm unable to reproduce. What version of Node are you running?

**Comment by webular** [comment]
`
v6.9.1
`

**Comment by webular** [comment]
Your example doesn't seem to be working for me either.  I see `"An unexpected error has occurred."`
when i visit https://next-apollo-example-oxuygbsyft.now.sh/

**Comment by ads1018** [comment]
Turns out I'm running an older version of Node than you are. I updated my version of node and now I see the error. Looking into this.

**Comment by ads1018** [comment]
@webular Pushed up a fix :) Try again and let me know if it works for you.

**Comment by webular** [comment]
works great.  thx!  looking forward to running with this.

**Comment by ads1018** [comment]
![high-five-cat_o_646881](https://cloud.githubusercontent.com/assets/555740/12178911/1b37fa92-b542-11e5-8ce7-91b89aa3b4a1.gif)
