### ISSUE TITLE
Headers passed to ApolloClient

### ISSUE THREAD

**Issue by sbking** [ads1018/next-apollo-example#3]
Regarding this line:

https://github.com/ads1018/next-apollo-example/blob/develop/lib/initClient.js#L8

I cannot find in Apollo's documentation or code any reference to passing headers as an option on ApolloClient. It seems like headers are supposed to be passed to the createNetworkInterface options directly:

http://dev.apollodata.com/core/network.html#createNetworkInterface

Nothing seems to change if I simply remove the headers option from the ApolloClient, but if I move it to the createNetworkInterface options it causes an SSL error on the server. Could you clarify this for me?

**Comment by ads1018** [comment]
@sbking You're right - it absolutely ought to be passed to createNetworkInterface. Good spot. I also just tried to move it to createNetworkInterface and I get the same SSL error. It seems like graph.cool doesn't like this getting passed for some reason though. I'm going to bring this up with the folks at graph.cool and see if they have any insight.

**Comment by ads1018** [comment]
@sbking you can follow along progress on this issue here: https://github.com/graphcool/console/issues/610

**Comment by ads1018** [comment]
@sbking Graph.cool doesn't support passing request headers to createNetworkInterface but it should work if you host your own graphql server. I'm going to close this but if you encounter this issue with your own hosted graphql server as well please let me know. I've updated the example: https://github.com/ads1018/next-apollo-example/blob/develop/lib/initClient.js#L13
