### ISSUE TITLE
No Access Origin

### ISSUE THREAD

**Issue by DanielRSnell** [ads1018/next-apollo-example#6]
When I attempt to use my server i am currently getting the following response: 

Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 405. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by ads1018** [comment]
Hey @DanielRSnell - I'm unable to reproduce this error. Not sure what's going on. Perhaps try nuking `node_modules` and running `npm install` again.
