### ISSUE TITLE
Delay rendering page until all components are ready with data

### ISSUE THREAD

**Issue by alexhillel** [ads1018/next-apollo-example#8]
When the About page is rendered server-side, and you then navigate to the Home page client-side, is there any way to defer rendering of the page until the page's components have their data available? 

I'd like to avoid component-level 'Loading' messages, and integrate with a loading indicator like nprogress (as per the with-loading example included with Next.js), so that each page comes into view fully rendered and without elements popping into view.

**Comment by ads1018** [comment]
React will soon support the ability to defer rendering with react "suspense". Until that api is stable, you could prefetch the data on your about page with the help of [data-prefetch-link](https://www.npmjs.com/package/data-prefetch-link)
